#!/bin/sh

echo "-----> Generating httpasswd $AUTH_USER"
htpasswd -Bbn "$AUTH_USER" "$AUTH_PASSWORD" > /verdaccio/conf/htpasswd

echo "-----> Starting verdaccio"
$APPDIR/bin/verdaccio --config /verdaccio/conf/config.yaml --listen http://0.0.0.0:5000
