#!/bin/sh

echo "-----> Generating httpasswd $AUTH_USER"
htpasswd -Bbn "$AUTH_USER" "$AUTH_PASSWORD" > ./htpasswd

echo "-----> Starting verdaccio"
$APPDIR/bin/verdaccio --config ./config.yaml --listen http://0.0.0.0:5000
